[build]
command = "yarn build"
publish = "dist"

[dev]
framework = "astro"
command = "yarn dev"
autoLaunch = false

[[plugins]]
package = "netlify-plugin-minify-html"
    [plugins.inputs.minifierOptions]
    collapseWhitespace = true
    minifyJS = true
    processScripts = ["module"]