[build]
  command = "yarn build"
  publish = "dist"

[dev]
  framework = "astro"
  command = "yarn dev"
  autoLaunch = false

[[plugins]]
  package = "netlify-plugin-minify-html"
    [plugins.inputs.minifierOptions]
    collapseWhitespace = true
    minifyJS = true
    processScripts = ["module"]

[[redirects]]
  from = "/screenshot/*"
  to = "https://sngrapi.netlify.app/image/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[headers]]
  for = "/screenshot/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# Build Processing 
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = false
  
[build.processing.images]
  compress = false