[build]
  command = "yarn build"
  publish = "dist"

[dev]
  framework = "astro"
  command = "yarn dev"
  autoLaunch = false

# Build Processing 
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = false
  
[build.processing.images]
  compress = false

# internal/resource rewrites & redirects
[[redirects]]
  from = "/rss"
  to = "/rss.xml"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap"
  to = "/sitemap-index.xml"
  status = 200
  force = true

[[redirects]]
  from = "/screenshot/*"
  to = "https://sngrapi.netlify.app/image/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[headers]]
  for = "/screenshot/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"


# all external redirects starts here
[[redirects]]
  from = "/radenpioneer"
  to = "https://radenpioneer.netlify.app"
  status = 301
  force = true

[[redirects]]
  from = "/image-api"
  to = "https://sngrapi.netlify.app"
  status = 301
  force = true

[[redirects]]
  from = "/repo"
  to = "https://github.com/sngrstudio/sngr.studio"
  status = 301
  force = true

[[redirects]]
  from = "/github"
  to = "https://github.com/sngrstudio"
  status = 301
  force = true

[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/sngrstudio/"
  status = 301
  force = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com"
  status = 301
  force = true

[[redirects]]
  from = "/atribusi/storyset"
  to = "https://storyset.com/online"
  status = 301
  force = true

[[redirects]]
  from = "/about/slide"
  to = "https://www.figma.com/proto/ZlsU4GiBiIsb9LI32SOYCH/Company-Profile?node-id=3%3A5&scaling=contain&page-id=0%3A1"
  status = 301
  force = true

[[redirects]]
  from = "/about/pdf"
  to = "/files/sngr-company-profile.pdf"
  status = 200
  force = true