[build]
  command = "pnpm run build"
  publish = "dist"

[dev]
  framework = "astro"
  command = "pnpm run dev"
  autoLaunch = false

[[redirects]]
  from = "/"
  to = "/under-construction"
  status = 301
  force = true
