name: SNGR Studio
slogan: Persembahan terbaik, dari teknologi web terdepan.
description: >-
  SNGR Studio membantu bisnis, UMKM, dan individual
  untuk meningkatkan presensi di dunia maya melalui
  tampilan website yang ringan, cepat dan aman.
legal:
  name: PT. Karya Muda Mentaya
